# Generated by Django 5.0.2 on 2025-06-09 10:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код направления')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('budget_places', models.PositiveIntegerField(default=0, verbose_name='Количество бюджетных мест')),
                ('contract_places', models.PositiveIntegerField(default=0, verbose_name='Количество контрактных мест')),
                ('current_budget_applications', models.PositiveIntegerField(default=0, verbose_name='Текущее количество бюджетных заявлений')),
                ('current_contract_applications', models.PositiveIntegerField(default=0, verbose_name='Текущее количество контрактных заявлений')),
            ],
            options={
                'verbose_name': 'Направление подготовки',
                'verbose_name_plural': 'Направления подготовки',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предмета')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код предмета')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProgramSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Минимальный балл')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный предмет')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='programs_app.studyprogram')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs_app.subject')),
            ],
            options={
                'verbose_name': 'Предмет направления',
                'verbose_name_plural': 'Предметы направлений',
                'ordering': ['program', 'subject'],
                'unique_together': {('program', 'subject')},
            },
        ),
    ]
