# Generated by Django 5.0.2 on 2025-06-12 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs_app', '0002_studyprogram_education_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyprogram',
            name='budget_places',
        ),
        migrations.RemoveField(
            model_name='studyprogram',
            name='contract_places',
        ),
        migrations.RemoveField(
            model_name='studyprogram',
            name='current_budget_applications',
        ),
        migrations.RemoveField(
            model_name='studyprogram',
            name='current_contract_applications',
        ),
    ]
