# Generated by Django 5.0.2 on 2025-06-12 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications_app', '0002_remove_application_enrollment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programpreference',
            name='enrollment_type',
        ),
    ]
