# Generated by Django 5.0.2 on 2025-06-12 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications_app', '0003_remove_programpreference_enrollment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
    ]
