# Generated by Django 5.0.2 on 2025-06-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications_app', '0005_applicationphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='education_form',
            field=models.CharField(choices=[('bachelor_full', 'Очная форма обучения бакалавриат'), ('specialist_full', 'Очная форма обучения специалитет'), ('master_full', 'Очная форма обучения магистратура'), ('master_part', 'Очно-заочная форма обучения магистратура'), ('bachelor_part', 'Заочная форма обучения бакалавриат')], default='bachelor_full', max_length=32, verbose_name='Форма обучения'),
        ),
    ]
