# Generated by Django 5.0.2 on 2025-06-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications_app', '0006_application_education_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='notarized_passport_scan',
            field=models.FileField(blank=True, null=True, upload_to='notarized_passports/', verbose_name='Нотариальный перевод ID карты/паспорта'),
        ),
        migrations.AlterField(
            model_name='application',
            name='passport_scan',
            field=models.FileField(blank=True, null=True, upload_to='passports/', verbose_name='Скан паспорта'),
        ),
    ]
